# Generated by Django 4.0.4 on 2022-05-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_artist_image_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
